version: '3.7'
services:
  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$SERVICE_DB_DATABASE
      - MYSQL_PASSWORD=$SERVICE_DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$SERVICE_DB_PASSWORD
    volumes:
      - mysqld-data:/var/lib/mysql
    network_mode: host

volumes:
  mysqld-data:
