version: '3.7'
services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$SERVICE_DB_DATABASE
      - MYSQL_PASSWORD=$SERVICE_DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$SERVICE_DB_PASSWORD
    ports:
      - $SERVICE_DB_PORT:3306
    volumes:
      - mysqld-data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.5'
          memory: 200M
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 500M
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: LISTENER_DOCKER://:29092,LISTENER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka

volumes:
  mysqld-data:
