// Code generated by MockGen. DO NOT EDIT.
// Source: vessel.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	util "github.com/joshiaj7/vessel-management/internal/util"
	entity "github.com/joshiaj7/vessel-management/module/core/entity"
	param "github.com/joshiaj7/vessel-management/module/core/param"
)

// MockVesselUsecase is a mock of VesselUsecase interface.
type MockVesselUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockVesselUsecaseMockRecorder
}

// MockVesselUsecaseMockRecorder is the mock recorder for MockVesselUsecase.
type MockVesselUsecaseMockRecorder struct {
	mock *MockVesselUsecase
}

// NewMockVesselUsecase creates a new mock instance.
func NewMockVesselUsecase(ctrl *gomock.Controller) *MockVesselUsecase {
	mock := &MockVesselUsecase{ctrl: ctrl}
	mock.recorder = &MockVesselUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVesselUsecase) EXPECT() *MockVesselUsecaseMockRecorder {
	return m.recorder
}

// CreateVessel mocks base method.
func (m *MockVesselUsecase) CreateVessel(ctx context.Context, params *param.CreateVessel) (*entity.Vessel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVessel", ctx, params)
	ret0, _ := ret[0].(*entity.Vessel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVessel indicates an expected call of CreateVessel.
func (mr *MockVesselUsecaseMockRecorder) CreateVessel(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVessel", reflect.TypeOf((*MockVesselUsecase)(nil).CreateVessel), ctx, params)
}

// GetVessel mocks base method.
func (m *MockVesselUsecase) GetVessel(ctx context.Context, params *param.GetVessel) (*entity.Vessel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVessel", ctx, params)
	ret0, _ := ret[0].(*entity.Vessel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVessel indicates an expected call of GetVessel.
func (mr *MockVesselUsecaseMockRecorder) GetVessel(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVessel", reflect.TypeOf((*MockVesselUsecase)(nil).GetVessel), ctx, params)
}

// ListVessels mocks base method.
func (m *MockVesselUsecase) ListVessels(ctx context.Context, params *param.ListVessels) ([]*entity.Vessel, *util.OffsetPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVessels", ctx, params)
	ret0, _ := ret[0].([]*entity.Vessel)
	ret1, _ := ret[1].(*util.OffsetPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVessels indicates an expected call of ListVessels.
func (mr *MockVesselUsecaseMockRecorder) ListVessels(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVessels", reflect.TypeOf((*MockVesselUsecase)(nil).ListVessels), ctx, params)
}

// UpdateVessel mocks base method.
func (m *MockVesselUsecase) UpdateVessel(ctx context.Context, params *param.UpdateVessel) (*entity.Vessel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVessel", ctx, params)
	ret0, _ := ret[0].(*entity.Vessel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVessel indicates an expected call of UpdateVessel.
func (mr *MockVesselUsecaseMockRecorder) UpdateVessel(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVessel", reflect.TypeOf((*MockVesselUsecase)(nil).UpdateVessel), ctx, params)
}
