// Code generated by MockGen. DO NOT EDIT.
// Source: voyage.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	util "github.com/joshiaj7/vessel-management/internal/util"
	entity "github.com/joshiaj7/vessel-management/module/core/entity"
	param "github.com/joshiaj7/vessel-management/module/core/param"
)

// MockVoyageUsecase is a mock of VoyageUsecase interface.
type MockVoyageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockVoyageUsecaseMockRecorder
}

// MockVoyageUsecaseMockRecorder is the mock recorder for MockVoyageUsecase.
type MockVoyageUsecaseMockRecorder struct {
	mock *MockVoyageUsecase
}

// NewMockVoyageUsecase creates a new mock instance.
func NewMockVoyageUsecase(ctrl *gomock.Controller) *MockVoyageUsecase {
	mock := &MockVoyageUsecase{ctrl: ctrl}
	mock.recorder = &MockVoyageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoyageUsecase) EXPECT() *MockVoyageUsecaseMockRecorder {
	return m.recorder
}

// CreateVoyage mocks base method.
func (m *MockVoyageUsecase) CreateVoyage(ctx context.Context, params *param.CreateVoyage) (*entity.Voyage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVoyage", ctx, params)
	ret0, _ := ret[0].(*entity.Voyage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVoyage indicates an expected call of CreateVoyage.
func (mr *MockVoyageUsecaseMockRecorder) CreateVoyage(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVoyage", reflect.TypeOf((*MockVoyageUsecase)(nil).CreateVoyage), ctx, params)
}

// GetVoyage mocks base method.
func (m *MockVoyageUsecase) GetVoyage(ctx context.Context, params *param.GetVoyage) (*entity.Voyage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVoyage", ctx, params)
	ret0, _ := ret[0].(*entity.Voyage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVoyage indicates an expected call of GetVoyage.
func (mr *MockVoyageUsecaseMockRecorder) GetVoyage(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVoyage", reflect.TypeOf((*MockVoyageUsecase)(nil).GetVoyage), ctx, params)
}

// ListVoyages mocks base method.
func (m *MockVoyageUsecase) ListVoyages(ctx context.Context, params *param.ListVoyages) ([]*entity.Voyage, *util.OffsetPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVoyages", ctx, params)
	ret0, _ := ret[0].([]*entity.Voyage)
	ret1, _ := ret[1].(*util.OffsetPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVoyages indicates an expected call of ListVoyages.
func (mr *MockVoyageUsecaseMockRecorder) ListVoyages(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVoyages", reflect.TypeOf((*MockVoyageUsecase)(nil).ListVoyages), ctx, params)
}

// UpdateVoyage mocks base method.
func (m *MockVoyageUsecase) UpdateVoyage(ctx context.Context, params *param.UpdateVoyage) (*entity.Voyage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVoyage", ctx, params)
	ret0, _ := ret[0].(*entity.Voyage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVoyage indicates an expected call of UpdateVoyage.
func (mr *MockVoyageUsecaseMockRecorder) UpdateVoyage(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVoyage", reflect.TypeOf((*MockVoyageUsecase)(nil).UpdateVoyage), ctx, params)
}
